-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: May 26, 2016 at 04:36 PM
-- Server version: 10.1.10-MariaDB
-- PHP Version: 7.0.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `newhorizons`
--

-- --------------------------------------------------------

--
-- Table structure for table `countries`
--

CREATE TABLE `countries` (
  `id` int(4) NOT NULL,
  `stad` varchar(255) NOT NULL,
  `land` varchar(255) NOT NULL,
  `vandring` tinyint(1) NOT NULL,
  `kanot` tinyint(1) NOT NULL,
  `backpacking` tinyint(1) NOT NULL,
  `safari` tinyint(1) NOT NULL,
  `skidor` tinyint(1) NOT NULL,
  `surfing` tinyint(1) NOT NULL,
  `dykning` tinyint(1) NOT NULL,
  `bergsklattring` tinyint(1) NOT NULL,
  `spa` tinyint(1) NOT NULL,
  `naturupplevelser` tinyint(1) NOT NULL,
  `solsemester` tinyint(1) NOT NULL,
  `yoga` tinyint(1) NOT NULL,
  `meditation` tinyint(1) NOT NULL,
  `hotell` tinyint(1) NOT NULL,
  `motell` tinyint(1) NOT NULL,
  `vandrarhem` tinyint(1) NOT NULL,
  `camping` tinyint(1) NOT NULL,
  `bedAndBreakfast` tinyint(1) NOT NULL,
  `kostnadTransport` float NOT NULL,
  `kostnadBoende` float NOT NULL,
  `levnadsKostnad` float NOT NULL,
  `distans` int(5) NOT NULL,
  `solTemp` tinyint(1) NOT NULL,
  `svalTemp` tinyint(1) NOT NULL,
  `kalltTemp` tinyint(1) NOT NULL,
  `bergigt` tinyint(1) NOT NULL,
  `plant` tinyint(1) NOT NULL,
  `oken` tinyint(1) NOT NULL,
  `skog` tinyint(1) NOT NULL,
  `narhetTillVatten` tinyint(1) NOT NULL,
  `sightseeing` tinyint(1) NOT NULL,
  `storstad` tinyint(1) NOT NULL,
  `historia` tinyint(1) NOT NULL,
  `religion` tinyint(1) NOT NULL,
  `utbildningssyfte` tinyint(1) NOT NULL,
  `matresa` tinyint(1) NOT NULL,
  `kontinent` varchar(240) NOT NULL,
  `flygplan` tinyint(1) NOT NULL,
  `tag` tinyint(1) NOT NULL,
  `buss` tinyint(1) NOT NULL,
  `annat` tinyint(1) NOT NULL,
  `img1` varchar(250) NOT NULL,
  `img2` varchar(250) NOT NULL,
  `img3` varchar(250) NOT NULL,
  `img4` varchar(250) NOT NULL,
  `img5` varchar(250) NOT NULL,
  `countryInfo` longtext NOT NULL,
  `cityInfo` longtext NOT NULL,
  `background` varchar(250) NOT NULL,
  `imgLink1` longtext NOT NULL,
  `imgLink2` longtext NOT NULL,
  `imgLink3` longtext NOT NULL,
  `imgLink4` longtext NOT NULL,
  `imgText1` varchar(250) NOT NULL,
  `imgText2` varchar(250) NOT NULL,
  `imgText3` varchar(250) NOT NULL,
  `imgText4` varchar(250) NOT NULL,
  `hotellText` varchar(250) NOT NULL,
  `flygText` varchar(250) NOT NULL,
  `aktivitetText` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `countries`
--

INSERT INTO `countries` (`id`, `stad`, `land`, `vandring`, `kanot`, `backpacking`, `safari`, `skidor`, `surfing`, `dykning`, `bergsklattring`, `spa`, `naturupplevelser`, `solsemester`, `yoga`, `meditation`, `hotell`, `motell`, `vandrarhem`, `camping`, `bedAndBreakfast`, `kostnadTransport`, `kostnadBoende`, `levnadsKostnad`, `distans`, `solTemp`, `svalTemp`, `kalltTemp`, `bergigt`, `plant`, `oken`, `skog`, `narhetTillVatten`, `sightseeing`, `storstad`, `historia`, `religion`, `utbildningssyfte`, `matresa`, `kontinent`, `flygplan`, `tag`, `buss`, `annat`, `img1`, `img2`, `img3`, `img4`, `img5`, `countryInfo`, `cityInfo`, `background`, `imgLink1`, `imgLink2`, `imgLink3`, `imgLink4`, `imgText1`, `imgText2`, `imgText3`, `imgText4`, `hotellText`, `flygText`, `aktivitetText`) VALUES
(15, 'Geneve', 'Schweiz', 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 'Europa', 1, 1, 1, 1, 'schweiz_country.jpg', 'train.jpg', 'dagsutflykt.jpg', 'boat.jpg', 'tasting.jpg', 'Schweiz, har tyska, franska och italienska som officiella språk. Klimatet där domineras av vindar i öst, väst, syd och mellaneuropeiskt lågtryck i norr. Temperaturen i sommaren ligger mellan 18-20 grader i dalarna och rund 10 grader på de högre höjderna. Det finns många höga bergstoppar (Alperna).\r\nSchweiz har Schweizisk franc som valuta. Visum krävs inte från svenska medborgare.', 'Genève är en stad i sydvästra Schweiz. Den är huvudstad i kantonen Genève och är, näst efter Zürich, den största staden i landet med 196 257 invånare inom stadsgränsen (2014). Den utbreder sig på bägge sidor av den sydvästra delen av Genèvesjön (Lac Léman). Det lokala huvudspråket är franska.\r\nGenève förknippas med Genèvekonventionen samt är känd som Jean-Jacques Rousseaus födelsestad och Jean Calvins hemstad. Staden är även känd för att vara den plats där Henri Dunant grundade Röda korset.', 'Switzerland.jpg', 'https://www.viatorcom.se/sv/7384/tours/Geneve/Dagsresa­till­Gruyeres­inklusive- Golden­Panoramic­Express­Train/d578­2510KT002', 'https://www.viatorcom.se/sv/7384/tours/Geneve/Chamonix­och­Mont­Blanc/d578­2510KT001', 'https://www.viatorcom.se/sv/7384/tours/Geneve/Geneva­City­Tour­and­Boat­Cruise/d5782510KTG207', 'https://www.viatorcom.se/sv/7384/tours/Geneve/Day­Trip­to­Gruyeres­with­Cheese­and- Chocolate­Tastings/d578­2510KTG352', 'Tågresa till Gruyères', 'Utflykt till Chamonix och Mont Blanc', 'Utflykt till Chamonix och Mont Blanc', 'Ost­ och chokladprovning', 'http://www.reseguiden.se/hotell/geneve/2660646', 'https://www.flygresor.se/schweiz/geneve', 'https://www.viatorcom.se/sv/7384/Geneve/d578­ttd'),
(16, 'Thessaloniki', 'Grekland', 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 'Europa', 1, 1, 1, 1, 'Thessaloniki.jpg', 'olympus.jpg', 'boat.jpg', 'walking.jpg', 'daytour.jpg', 'Grekland, officiella språket är grekiska och euro är valutan i landet. Grekland har ett typiskt medelhavsklimat, men med stora skillnader mellan norra och södra landet och mellan bergen och kusten samt inlandet. Snö och is är vanliga i det högre bergstrakterna men förekommer även i resten av Grekland.\r\nVid tillträde krävs inte ett visum från svenska medborgare men ett giltigt pass är viktigt.', 'Thessaloniki är Greklands näst största stad. Staden utgör utöver Greklands andra industriella, kommersiella, finansiella och kulturella centrum även sydöstra Europas viktigaste handels- och transportnav; detta gäller speciellt stadens hamn genom vilken majoriteten av Balkanländernas förnödenheter transporteras.\r\n\r\nThessaloniki utgör också en av Sydeuropas viktigaste universitetsstäder med en tillföljande stor andel studenter. Greklands äldsta och största moderna statliga universitet, Aristotelesuniversitetet i Thessaloniki[1] (grundat 1926) samt Makedoniens universitet[2] återfinns här, likaså den tekniska högskolan Alexandreio Technologiko Ekpaideutiko Idruma Thessalonikis. Utöver de statliga institutionerna finns även ett flertal privata oftast med koppling till eller som filialer av större europeiska eller amerikanska universitet.', 'Thessaloniki_background.jpg', 'https://www.viatorcom.se/sv/7384/tours/Thessaloniki/Mount-Olympus-Canyoning/d23853-11838P', 'https://www.viatorcom.se/sv/7384/tours/Thessaloniki/Sailboat-west-Sithonia-tour/d23853-11193P1', 'https://www.viatorcom.se/sv/7384/tours/Thessaloniki/Thessaloniki-Walking-Tour-and-Gastronomical-Experience/d23853-12485P1', 'https://www.viatorcom.se/sv/7384/tours/Thessaloniki/AMPHIPOLIS-PHILIPPI-KAVALA-ONE-DAY-TOUR/d23853-20715P1', 'Upplev Mount Olympus', 'Halkidiki båttrip', 'Halkidiki båttrip', 'Dagstur från Thessaloniki', 'http://www.reseguiden.se/hotell/thessaloniki/734077', 'https://www.flygresor.se/grekland/thessaloniki', 'https://www.viatorcom.se/sv/7384/Thessaloniki/d23853-ttd?activities=all'),
(18, 'Piraeus', 'Grekland', 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 'Europa', 1, 1, 1, 1, 'piraeus.jpg', 'bus_tour.jpg', 'full_day_tour.png', 'booze_cruise.jpg', 'seaside_tour.jpg', 'Grekland, officiella språket är grekiska och euro är valutan i landet. Grekland har ett typiskt medelhavsklimat, men med stora skillnader mellan norra och södra landet och mellan bergen och kusten samt inlandet. Snö och is är vanliga i det högre bergstrakterna men förekommer även i resten av Grekland.\r\nVid tillträde krävs inte ett visum från svenska medborgare men ett giltigt pass är viktigt.', 'Pireus är en hamnstad i Grekland, belägen vid Saroniska viken. Ända sedan antiken har den fungerat som Atens hamn och är numera sammanvuxen med Aten. Här ligger fotbollstadium Karaïskákis-Stadion som är hemmaplan för klubblaget Olympiakos och Greklands herrlandslag i fotboll.', 'piraeus_background.jpg', 'https://www.getyourguide.com/athens-l91/athens-and-piraeus-hop-on-hop-off-bus-tour-t49048/', 'https://www.getyourguide.com/athens-l91/full-day-tour-of-the-saronic-islands-from-athens-t5991/', 'https://www.getyourguide.com/athens-l91/athens-booze-cruise-t56070/', 'https://www.getyourguide.com/piraeus-l759/piraeus-seaside-tour-with-electric-bike-t52175/', 'Hop-on Hop-off', 'Heldags tur', 'Heldags tur', 'Rundtur vid havet', 'http://www.reseguiden.se/hotell/pireus/255274', 'http://www.ferries.gr/greek-islands-ferry/ferry_piraeus.htm', 'https://www.getyourguide.com/s/?q=piraeus&lc=l759'),
(20, 'Timbuktu', 'Mali', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 'Afrika', 0, 0, 0, 0, 'timbuktu.jpg', 'sankore.jpg', 'dyingerey.jpg', 'heinrich.jpg', 'yahiya.jpg', 'Mali, franska är det officiella språket i landet. Klimatet är hett och torrt i hela Mali. I Saharaöknen i norr regnar det mycket sällan, vissa år faller ingen nederbörd alls. I Sahelområdet längre söderut är klimatet mindre torrt och medeltemperaturen är något lägre. I den sydligaste delen av landet är det svalare och fuktigare. I Mali är valutan CFA-franc.\r\nAlla nationaliteter behöver visum för inresa till Mali. Ett visum är giltigt för en inresa i landet och gäller i en månad från inresedagen i Mali, men kan förlängas på Migrationsverket i Bamako eller på en malisk polisstation. Visum kan erhållas upp till tre månader innan resan och erhålls från närmaste maliska ambassad eller konsulat. Vaccination mot gula febern är obligatorisk.', 'Timbuktu är en stad nära floden Niger i det västafrikanska landetMali. Kommunens befolkning uppgick till strax över 60 000 invånare 2013. Timbuktu är administrativ huvudort för en region med samma namn som staden. Timbuktu har en lång historia som handelsplats mellan Nordafrika och Afrika söder om Sahara. Namnet Timbuktu kom i Europa att bli en metafor för en fjärran, exotisk plats.', 'timbuktu_background.jpg', 'https://www.lonelyplanet.com/mali/niger-river-route/timbuktu-tombouctou/sights/religious/sankore-mosque', 'https://www.lonelyplanet.com/mali/niger-river-route/timbuktu-tombouctou/sights/architecture/dyingerey-ber-mosque', 'https://www.lonelyplanet.com/mali/niger-river-route/timbuktu-tombouctou/sights/arts-culture-literary/heinrich-barth-s-house', 'https://www.lonelyplanet.com/mali/niger-river-route/timbuktu-tombouctou/sights/architecture/sidi-yahiya-mosque', 'Upplev Sankoré', 'Imponerande arkitektur', 'Imponerande arkitektur', 'Gammal moské', 'https://www.tripadvisor.se/Hotels-g304007-Timbuktu_Tombouctou_Region-Hotels.html ', 'http://www.allaflygbiljetter.se/flyg/timbuktu_tom', 'https://www.lonelyplanet.com/mali/niger-river-route/timbuktu-tombouctou/things-to-do'),
(21, 'Alexandria', 'Egypten', 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 'Afrika', 1, 0, 0, 1, 'Alexandria.jpg', 'overnight_trip.png', 'shore_excursion.png', 'alamain.png', 'private_trip.png', 'I Egypten är arabiska det officiella språket. Valutan som används är Egyptiska Pund (förkortas EGP eller LE). VISA och MasterCard kan användas på de flesta hotell och kryssningsfartyg och även vissa andra ställen. Egypten har ett torrt och varmt ökenklimat. På sommaren är det hett, men på vintern råder behagliga temperaturer. I öknen är nätterna kalla under vintertid. Vid Medelhavskusten är klimatet fuktigt och där faller regn på vintern. Under våren blåser hårda och torra sandvindar, från öknen i sydväst\r\nFör att resa till Egypten behöver du som svensk medborgare ha visum. Ett egyptiskt visum kan du få på Egyptiska ambassaden i Stockholm innan resan eller på flygplatsen när du anländer. Om du ska resa direkt till någon av följande turistorter behöver du inte ha visum. Du får stanna i två veckor på orten utan visum: Sharm El Sheikh, Dahab, NuweibaTaba\r\n\r\nDricks kallas Baksheesh, Se alltid till att ha en del småpengar, 1-pundsedlar och 50 piasters-sedlar i fickorna till t ex offentliga toaletter. Dricksen beräknas till totalt 50 SEK per dag.', 'Alexandria är Egyptens näst största stad och en viktig hamnstad och industristad [3] men även en betydande turiststad och badort. Alexandria är belägen i landets norra del vid Nilens utlopp i Medelhavet. Staden var Egyptens huvudstad under nästan 1000 år och platsen för Fyrtornet på Faros, ett av de gamla Världens sju underverk, och Museion med Biblioteket i Alexandria, den antika världens största bibliotek.\r\nIdag är Alexandria landets största hamn där cirka 80 % av Egyptens import och export omsätts.', 'Alexandria_background.jpg', 'http://www.viator.com/tours/Alexandria/Overnight-Trip-to-Cairo-from-Alexandria-Port/d4376-18465P6', 'http://www.viator.com/tours/Alexandria/Shore-Excursion-Small-Group-Guided-Tour-in-Alexandria/d4376-19997P1', 'http://www.viator.com/tours/Alexandria/Day-Tour-to-Alamain-Museum-Visiting-the-Commonwealth-German-Cemetery/d4376-18465P2', 'http://www.viator.com/tours/Alexandria/Classic-Cairo-Private-Day-Trip-from-Alexandria/d4376-19426P6', 'Trip till Kairo', 'Guidad tur', 'Guidad tur', 'Klassisk privat dagstur', 'https://www.kayak.se/sem/hotels/destination/-c25321?lang=sv&gclid=CjwKEAjw9Zu5BRCS_OuVibujhQ0SJAD7t4KrdZ8zgKIeg2xQRPoAVPryXK2Hfysw1xETOEpXw0b7RxoCepnw_wcB', 'https://www.flygresor.se/egypten/alexandria', 'http://www.viator.com/Alexandria/d4376-ttd'),
(22, 'Giza', 'Egypten', 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 'Afrika', 1, 0, 0, 1, 'giza.jpg', 'nile_pharaoh.jpg', 'show_pyramids.jpg', 'sunset_ride.jpg', 'sailing.jpg', 'I Egypten är arabiska det officiella språket. Valutan som används är Egyptiska Pund (förkortas EGP eller LE). VISA och MasterCard kan användas på de flesta hotell och kryssningsfartyg och även vissa andra ställen. Egypten har ett torrt och varmt ökenklimat. På sommaren är det hett, men på vintern råder behagliga temperaturer. I öknen är nätterna kalla under vintertid. Vid Medelhavskusten är klimatet fuktigt och där faller regn på vintern. Under våren blåser hårda och torra sandvindar, från öknen i sydväst\r\nFör att resa till Egypten behöver du som svensk medborgare ha visum. Ett egyptiskt visum kan du få på Egyptiska ambassaden i Stockholm innan resan eller på flygplatsen när du anländer. Om du ska resa direkt till någon av följande turistorter behöver du inte ha visum. Du får stanna i två veckor på orten utan visum: Sharm El Sheikh, Dahab, NuweibaTaba\r\n\r\nDricks kallas Baksheesh, Se alltid till att ha en del småpengar, 1-pundsedlar och 50 piasters-sedlar i fickorna till t ex offentliga toaletter. Dricksen beräknas till totalt 50 SEK per dag.', 'Giza är den tredje största staden i Egypten, med 2 891 275 invånare (2006). Giza är mest känd för att vara av stor arkeologisk betydelse, och ligger längs med Nilens västra strand, ungefär 10 km sydväst på motsatta sidan av floden om centrala Kairo. Mest iögonfallande är Gizaplatån med sina pyramider, sfinxen och flera tempel som räknas som ett av antikens sju underverk. Dessa monument är belägna i öknen alldeles i utkanten av storstadsbebyggelsen.', 'giza_background.jpg', 'https://www.viatorcom.se/sv/7384/tours/Giza/Nile-Pharaoh-Dinner-Cruise-from-Giza/d23032-10124P9', 'https://www.viatorcom.se/sv/7384/tours/Giza/Sound-and-Light-Show-at-The-Pyramids-of-Giza/d23032-10124P11', 'https://www.viatorcom.se/sv/7384/tours/Giza/Sunset-Camel-or-Horse-Ride-by-the-Giza-Pyramids/d23032-26535P1', 'https://www.viatorcom.se/sv/7384/tours/Giza/Felucca-Sailing-Ride-on-The-Nile-from-Giza/d23032-10124P13', 'Måltidskryssning', 'Ljusshow vid pyramiderna', 'Ljusshow vid pyramiderna', 'Segling på Nilen', 'http://www.reseguiden.se/hotell/giza/360995', 'https://www.expedia.se/Flyg-Till-Giza.d178624.Reseguide-Flyg', 'https://www.viatorcom.se/sv/7384/Giza/d23032-ttd'),
(23, 'Kairo', 'Egypten', 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 'Afrika', 1, 0, 0, 1, 'Kairo.jpg', 'flodkryssning_kairo.jpg', 'pyramider_kairo.jpg', 'food_kairo.jpg', 'safari_kairo.jpg', 'I Egypten är arabiska det officiella språket. Valutan som används är Egyptiska Pund (förkortas EGP eller LE). VISA och MasterCard kan användas på de flesta hotell och kryssningsfartyg och även vissa andra ställen. Egypten har ett torrt och varmt ökenklimat. På sommaren är det hett, men på vintern råder behagliga temperaturer. I öknen är nätterna kalla under vintertid. Vid Medelhavskusten är klimatet fuktigt och där faller regn på vintern. Under våren blåser hårda och torra sandvindar, från öknen i sydväst\r\nFör att resa till Egypten behöver du som svensk medborgare ha visum. Ett egyptiskt visum kan du få på Egyptiska ambassaden i Stockholm innan resan eller på flygplatsen när du anländer. Om du ska resa direkt till någon av följande turistorter behöver du inte ha visum. Du får stanna i två veckor på orten utan visum: Sharm El Sheikh, Dahab, NuweibaTaba\r\n\r\nDricks kallas Baksheesh, Se alltid till att ha en del småpengar, 1-pundsedlar och 50 piasters-sedlar i fickorna till t ex offentliga toaletter. Dricksen beräknas till totalt 50 SEK per dag.', 'Kairo är huvudstad i Egypten. Staden ligger vid Nilen, cirka 150 kilometer in i landet från den egyptiska Medelhavskusten, ungefär där det väldiga Nildeltat övergår i den smalare Nildalen. Kairos storstadsområde är det folkrikaste i Afrika, och inkluderar bland annat Giza med dess berömda pyramider.', '', 'https://www.viatorcom.se/sv/7384/tours/Kairo/Flodkryssning-med-middag-pa-Nilen/d782-3124CAI16', 'https://www.viatorcom.se/sv/7384/tours/Kairo/Privat-rundtur-Pyramiderna-och-Sfinxen-i-Giza-Egyptiska-museet-Khan-el-Khalili-basaren/d782-3124CAI01', 'https://www.viatorcom.se/sv/7384/tours/Kairo/Local-Egyptian-Food-Tasting-and-Learning-From-Cairo/d782-11860P2', 'https://www.viatorcom.se/sv/7384/tours/Kairo/Safari-tour-on-a-horse-or-camel-for-sunset-at-Giza/d782-18966P43', 'Flodkryssning med mat', 'Rundtur i pyramiderna', 'Rundtur i pyramiderna', 'Safari på kamel/häst', 'http://www.reseguiden.se/hotell/kairo/360630', 'https://www.flygresor.se/egypten/kairo', 'https://www.viatorcom.se/sv/7384/Kairo/d782-ttd'),
(24, 'Aten', 'Grekland', 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 'Europa', 1, 1, 1, 1, 'aten.jpg', 'bar_hopping.jpg', 'hop_on_off.jpg', 'Akropolis.jpg', 'evening_tour.jpg', 'Grekland, officiella språket är grekiska och euro är valutan i landet. Grekland har ett typiskt medelhavsklimat, men med stora skillnader mellan norra och södra landet och mellan bergen och kusten samt inlandet. Snö och is är vanliga i det högre bergstrakterna men förekommer även i resten av Grekland.\r\n\r\nVid tillträde krävs inte ett visum från svenska medborgare men ett giltigt pass är viktigt.', 'Aten är huvudstaden och den största staden i Grekland med 4,2 miljoner invånare (uppgift från 2002).\r\nStaden växte otroligt mycket från andra världskriget fram till år 1980. På grund av detta har oron ökat för överbefolkning och luftföroreningar, vilket staden även har blivit känd för under senare år. Detta är något staden kämpar starkt emot, och staten har spenderat mycket pengar och energi för att få bukt med problemen.\r\n\r\nI och med sommar-OS 2004 byggdes mängder av tunnelbanelinjer, gator stängdes av för trafik och innerstaden rustades upp. Moderna motorvägar och en modern vägring har också byggts och tagits i bruk runt staden.\r\n\r\nDen mest centrala delen av Aten är Syntagma, Konstitutionstorget, där bland annat det grekiska parlamentet ligger. Syntagma är även ett av turisternas favoritmål, eftersom det även bjuds på en hel del kulturminnen. I området finns även flera museer. Tunnelbanestationen Syntagma, i mitten av Syntagmaplatsen, pryds av fynd från förhistorisk, antik och klassisk tid från platsens tunnelbaneutgrävningar, vilket ger intryck av museum. Det samma gäller andra t-banestationer i Atens centrala delar.', 'aten_background.jpg', 'https://www.viatorcom.se/sv/7384/tours/Aten/Athens-Bar-Hopping-Tour/d496-6956BARHOP', 'https://www.viatorcom.se/sv/7384/tours/Aten/Sights-of-Athens-Hop-on-Hop-Off-Classic-tour/d496-8391P3', 'https://www.viatorcom.se/sv/7384/tours/Aten/Gangtur-pa-Akropolis-med-Syntagmatorget-och-stadens-historiska-centrum/d496-2906ATHACRO', 'https://www.viatorcom.se/sv/7384/tours/Aten/An-evening-stroll/d496-18204P1', 'Prova olika barer', 'Klassisk tur av Aten', 'Klassisk tur av Aten', 'kvällstur av Aten', 'http://www.reseguiden.se/hotell/aten/264371 ', 'https://www.flygresor.se/grekland/aten?&gclid=CjwKEAjw9Zu5BRCS_OuVibujhQ0SJAD7t4KrkRay92Wi5mQ2dPSDGx9LWoyWERtkc2F4eyqNXx4w0RoCaG3w_wcB', 'https://www.viatorcom.se/sv/7384/Aten/d496-ttd '),
(26, 'Barcelona', 'Spanien', 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2168, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 'Europa', 1, 1, 1, 1, 'barcelona0.jpg', 'biljetter-till-rundtur.jpg', 'flamenco.jpg', 'parasailing.jpg', 'water-park.jpg', 'Spanien, har euro som valuta. Språk som talas i Spanien är spanska/kastilianska, katalanska, galiciska och baskiska. Klimatet varierar kraftigt mellan landets olika delar. Spanien har flera olika klimatzoner, från subtropiskt klimat i söder till det svala och regniga Atlantklimatet. Visum krävs inte.\r\n\r\nVarje år hålls en festival i en stad som heter Buñol, Valencia i Spanien under den sista onsdagen i augusti. Det är ett tomatkrig, där 30-40 000 människor ställer upp. Det brukar användas ungefär 120 ton övermogna tomater till kriget som varar i 1-2 timmar.', 'Barcelona är en stad och kommun belägen vid Kataloniens kust mellan floderna Llobregats och Besòs mynningar, 160 kilometer söder om franska gränsen. Barcelona är huvudstad i den autonoma regionen Katalonien men även för provinsen Barcelona samt grevskapet Barcelonès. Invånarantalet uppgick år 2009 till 1 638 103. Inkluderas de närmaste förstäderna är invånarantalet ungefär 3 miljoner, med satellitstäder cirka 5 miljoner. Staden är Spaniensnäst största stad, efter Madrid, samt den mest industrialiserade. Barcelona är även en av västvärldens mest tätbefolkade storstäder. Staden är idag en stor turiststad, och enbart under 2006 ökade antalet turister med över en miljon från föregående år. Både katalanska och spanska är officiella språk.', 'Barcelonabackground.jpg', 'https://www.viatorcom.se/sv/7384/tours/Barcelona/Biljetter-till-rundtur-och-museet-pa-FC-Barcelonas-fotbollsstadion/d562-2140FCBCN \r\n', 'https://www.viatorcom.se/sv/7384/tours/Barcelona/Flamencokvaell-pa-Tablao-Cordobes/d562-2140FLAMENCO \r\n', 'https://www.viatorcom.se/sv/7384/tours/Barcelona/Flamencokvaell-pa-Tablao-Cordobes/d562-2140FLAMENCO \r\n', 'https://www.viatorcom.se/sv/7384/tours/Barcelona/Illa-Fantasia-Water-and-Theme-Park-Tickets-with-Shuttle/d562-2140FANTASIA \r\n', 'Rundtur och museet på FC Barcelonas fotbollsstation', 'Flamencokväll på Tablao Cordobés', 'Fallskärmssegling ', 'Illa Fantasia water park ', 'http://www.reseguiden.se/s?destination_id=3128760&date_from=2016-05-03:2016-05-03&adults=1&date_to=2016-05-04:2016-05-04&product_type=hotel  ', 'http://www.momondo.se/flightsearch/?Search=true&TripType=2&SegNo=2&SO0=STO&SD0=BCN&SDP0=18-05-2016&SO1=BCN&SD1=STO&SDP1=23-05-2016&AD=1&TK=ECO&DO=false&NA=false#Search=true&TripType=2&SegNo=2&SO0=STO&SD0=BCN&SDP0=18-05-2016&SO1=BCN&SD1=STO&SDP1=23-05', 'https://www.viatorcom.se/sv/7384/Barcelona/d562-ttd?activities=all '),
(27, 'Madrid', 'Spanien', 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 'Europa', 1, 1, 1, 1, 'Madrid0.jpg', 'cooking.jpg', 'rundtur.jpg', 'gocar-tour.jpg', 'hot-air-balloon.jpg', 'Spanien, har euro som valuta. Språk som talas i Spanien är spanska/kastilianska, katalanska, galiciska och baskiska. Klimatet varierar kraftigt mellan landets olika delar. Spanien har flera olika klimatzoner, från subtropiskt klimat i söder till det svala och regniga Atlantklimatet. Visum krävs inte.\r\n\r\nVarje år hålls en festival i en stad som heter Buñol, Valencia i Spanien under den sista onsdagen i augusti. Det är ett tomatkrig, där 30-40 000 människor ställer upp. Det brukar användas ungefär 120 ton övermogna tomater till kriget som varar i 1-2 timmar.', 'Madrid är Spaniens huvudstad och den största staden på Iberiska halvön. Med sina 3,2 miljoner invånare i staden, och 6 miljoner i storstadsområdet, är Madrid en av de folkrikaste städerna inom EU. Madrid är beläget på vänstra stranden av Manzanares, ett litet tillflöde till Tajos biflod Jarama.', 'madridbackground.jpg', 'https://www.viatorcom.se/sv/7384/tours/Madrid/Madrid-Cooking-Class-Learn-How-to-Make-Paella/d566-5830TSCCIM', 'https://www.viatorcom.se/sv/7384/tours/Madrid/Hoppa-pahoppa-av-rundtur-i-Madrid/d566-2140MADRIDHOPON ', 'https://www.viatorcom.se/sv/7384/tours/Madrid/Madrid-GPS-Guided-GoCar-Tour/d566-5893MADGOCAR ', 'https://www.viatorcom.se/sv/7384/tours/Madrid/Hot-Air-Balloon-Ride-over-Madrids-Guadarrama-Regional-Park/d566-5998BALLOON ', 'Madrid cooking class', 'Rundtur i Madrid med valfri matprovning', 'Rundtur i Madrid med valfri matprovning', 'Luftballongtur över Madrid', 'http://www.reseguiden.se/s?destination_id=3117735&date_from=2016-05-03:2016-05-03&adults=1&date_to=2016-05-04:2016-05-04&product_type=hotel ', 'http://www.momondo.se/flightsearch/?Search=true&TripType=2&SegNo=2&SO0=STO&SD0=BCN&SDP0=18-05-2016&SO1=BCN&SD1=STO&SDP1=23-05-2016&AD=1&TK=ECO&DO=false&NA=false#Search=true&TripType=2&SegNo=2&SO0=STO&SD0=MAD&SDP0=18-05-2016&SO1=MAD&SD1=STO&SDP1=23-05', 'https://www.viatorcom.se/sv/7384/Madrid/d566-ttd?activities=all '),
(41, 'Basel', 'Schweiz', 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 'Europa', 1, 1, 1, 1, 'basel.jpg', 'vattenpark.png', 'gokart.png', 'zoo.png', 'vattenfall.png', 'Schweiz, har tyska, franska och italienska som officiella språk. Klimatet där domineras av vindar i öst, väst, syd och mellaneuropeiskt lågtryck i norr. Temperaturen i sommaren ligger mellan 18-20 grader i dalarna och rund 10 grader på de högre höjderna. Det finns många höga bergstoppar (Alperna). Schweiz har Schweizisk franc som valuta. Visum krävs inte från svenska medborgare. Barn som inte haft eller tidigare vaccinerats mot påssjuka, mässling eller röda hund bör vaccineras innan avresa.', 'Basel är Schweiz tredje största stad med cirka 171 000 invånare (2012), vid gränsen till Frankrike och Tyskland, tillika administrativ huvudort för kantonen Basel-Stadt. Huvudnäringen är kemisk industri men staden är även känd för mellanstatligt samarbete i finanssektorn.', 'background_basel.jpg', 'http://www.viator.com/tours/Basel/Water-Park-included-Ticket-and-transfer-roundtrip/d5010-30201P13 ', 'http://www.viator.com/tours/Basel/Go-Kart-Racing-included-Hotel-pick-up-and-drop-off/d5010-30201P14', 'http://www.viator.com/tours/Basel/Basel-Zoo/d5010-30201P5', 'http://www.viator.com/tours/Basel/Rhein-Fall-half-day-trip-and-Boat-Ticket-with-Hotel-Pick-and-Drop-Off-Included/d5010-30201P6', 'Vattenpark', 'Go-kart', 'Zoo', 'Tur till vattenfall', 'http://www.reseguiden.se/hotell/basel/2661604', 'http://www.skyscanner.se/flyg-till/bsl/billiga-flyg-till-basel-mulhouse-freiburg-flygplats.html', 'http://www.viator.com/Basel/d5010-ttd'),
(42, 'Zurich', 'Schweiz', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Europa', 0, 0, 0, 0, 'zurich.jpg', 'choklad.png', 'alptur.png', 'stadstur.png', 'glacier.png', 'Schweiz, har tyska, franska och italienska som officiella språk. Klimatet där domineras av vindar i öst, väst, syd och mellaneuropeiskt lågtryck i norr. Temperaturen i sommaren ligger mellan 18-20 grader i dalarna och rund 10 grader på de högre höjderna. Det finns många höga bergstoppar (Alperna). Schweiz har Schweizisk franc som valuta. Visum krävs inte från svenska medborgare. Barn som inte haft eller tidigare vaccinerats mot påssjuka, mässling eller röda hund bör vaccineras innan avresa.', 'Zürich är den största staden i Schweiz med 398 575 invånare (december 2013). Zürich är huvudstad i kantonen med 1 274 384 invånare. Staden ligger vid Zürichsjön.\r\n\r\nZürich blev medlem av det schweiziska edsförbundet år 1351. Det Schweiz-svenska företaget ABB har sitt huvudkontor här.', 'zurich_background.jpg', 'http://www.viator.com/tours/Zurich/Small-Group-Chocolate-and-Sweets-Walking-Tour-of-Zurichs-Old-Town/d577-6143ZURICH', 'http://www.viator.com/tours/Zurich/2-Day-Alps-Tour-from-Zurich-Mt-Pilatus-and-Mt-Titlis/d577-3885SWSUM02', 'http://www.viator.com/tours/Zurich/The-Great-Tour-of-Zurich/d577-2460CITB', 'http://www.viator.com/tours/Zurich/Private-Guided-Glacier-Express-1-day-Tour-from-Zurich/d577-8283P7', 'Choklad-rundtur', '2-dagars alptur', '2-dagars alptur', 'Glaciär-express', 'http://www.reseguiden.se/hotell/zurich/2657896', 'https://www.flygresor.se/schweiz/zurich', 'http://www.viator.com/Zurich/d577-ttd'),
(43, 'Yokohama', 'Japan', 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 'Asien', 1, 0, 0, 0, 'yokohama.jpg', 'ninja.png', 'national_park.png', 'robot.png', 'berg.png', 'Japan, japanska är det officiella språket i japan och yen är valutan som används. Medeltemperaturen vintertid i Japan ligger på 5,1 ºC och sommartid 25,2 ºC. Regnperioden börjar i maj - juni och når de nordliga regionerna i slutet av juli. Under denna period är luftfuktigheten hög och temperaturen kan på vissa ställen stiga till 42 ºC. Svenska medborgare som önskar resa till Japan som längst 90 dagar behöver inte ansöka om inresevisum i förväg om syftet med resan är följande icke-avlönade aktiviteter:\r\nturism, rekreation, utövande av amatörsport, besöka släktingar, deltaga i icke-betalda föredrag, konferenser eller möten, studier, affärsmöten, eller andra liknande aktiviteter. Journalister som reser till Japan för vistelse kortare än 90 dagar behöver inte heller ansöka om inrese-visum i förväg.\r\n \r\n· Det är oartigt att äta och dricka på gatan.\r\n· Om folk är för långsamma in i tåget så blir de inknuffade.\r\n· Butikerna är öppna dygnet runt\r\n· På vissa parkeringar så parkerar man bilen sen höjs rutan upp så att man tvingas betala för att få tillbaka bilen.\r\n· Om ett tåg är försenat med minst 30 sekunder så får alla åka gratis.', 'Yokohama är residensstad i Kanagawa prefektur på ön Honshu i Japan. Staden har 3,7 miljoner invånare och är därmed Japans näst största stad. Yokohama ligger vid Tokyobuktens västra strand och är en av landets viktigaste hamnstäder. Den är en del av Stortokyo[2] och bildar tillsammans med Kawasaki i norr centrum för Keihin, Japans viktigaste industriregion. I staden finns stora stålverk, oljeraffinaderier, varv och bilindustrier och omfattande tillverkning av verktygsmaskiner, elektroniska produkter och konstfibrer. Yokohama har vidare flera universitet och en rad fackhögskolor. Stadens hamn är Japans största importhamn. I Yokohama fanns ett kungligt svenskt konsulat 1897-1998.\r\n', 'yokohama_background.jpg', 'http://www.viator.com/tours/Tokyo/Ninja-School-Ninja-for-a-Day/d334-6117TYO_JHTKNJ', 'http://www.viator.com/tours/Tokyo/Nikko-National-Park-Day-Trip-from-Tokyo/d334-2142TYO_F300_F308', 'http://www.viator.com/tours/Tokyo/Tokyo-Robot-Evening-Cabaret-Show/d334-2142TYODIN1G', 'http://www.viator.com/tours/Tokyo/Mt-Fuji-Day-Trip-including-Lake-Ashi-Sightseeing-Cruise-from-Tokyo/d334-2142TYO_F880_F830', 'Ninjaskola', 'Nikko nationalpark', 'Robotshow', 'Sightseeing Mt Fuji & Lake Ashi', 'http://www.reseguiden.se/hotell/yokohama/1848354', 'http://www.travellink.se/flyg/japan/yokohama', 'http://www.viator.com/Japan/d16-ttd'),
(44, 'Osaka', 'Japan', 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 'Asien', 1, 0, 0, 0, 'osaka.jpg', 'tempel.png', 'vandring.png', 'sushi.png', 'akvarium.png', 'Japan, japanska är det officiella språket i japan och yen är valutan som används. Medeltemperaturen vintertid i Japan ligger på 5,1 ºC och sommartid 25,2 ºC. Regnperioden börjar i maj - juni och når de nordliga regionerna i slutet av juli. Under denna period är luftfuktigheten hög och temperaturen kan på vissa ställen stiga till 42 ºC. Svenska medborgare som önskar resa till Japan som längst 90 dagar behöver inte ansöka om inresevisum i förväg om syftet med resan är följande icke-avlönade aktiviteter:\r\nturism, rekreation, utövande av amatörsport, besöka släktingar, deltaga i icke-betalda föredrag, konferenser eller möten, studier, affärsmöten, eller andra liknande aktiviteter. Journalister som reser till Japan för vistelse kortare än 90 dagar behöver inte heller ansöka om inrese-visum i förväg.\r\n \r\n· Det är oartigt att äta och dricka på gatan.\r\n· Om folk är för långsamma in i tåget så blir de inknuffade.\r\n· Butikerna är öppna dygnet runt\r\n· På vissa parkeringar så parkerar man bilen sen höjs rutan upp så att man tvingas betala för att få tillbaka bilen.\r\n· Om ett tåg är försenat med minst 30 sekunder så får alla åka gratis.', 'Osaka är Japans tredje största stad efter Tokyo och Yokohama, belägen på ön Honshus södra kust vid Osakabukten av Stilla havet. Den är byggd vid floderna Yodogawa och Yamatogawas utflöden i havet. Staden hade 2,6 miljoner invånare 2004. Osaka bildar tillsammans med bl.a. de intilliggande städerna Kobe och Kyoto ett sammanhängande storstadsområde med över 19 miljoner invånare, vilket utgör Japans näst viktigaste industri- och handelscentrum.', 'osaka_background.jpg', 'http://www.viator.com/tours/Osaka/Kyoto-Morning-Tour-of-Kinkakuji-Temple-Nijo-Castle-and-Kyoto-Imperial-Palace-from-Osaka/d333-2142OSA_P840', 'http://www.viator.com/tours/Osaka/Osaka-Full-Day-Walking-Tour-with-Osaka-River-Cruise/d333-2142OSA_P740', 'http://www.viator.com/tours/Osaka/Sushi-Cooking-Class-in-Osaka/d333-6806OSASUSHI', 'http://www.viator.com/tours/Osaka/Osaka-Aquarium-Kaiyukan-Admission-with-Osaka-Bay-Cruise/d333-2142OSA_P601', 'Tempel- och palatstur', 'Vandring och båttur', 'Sushi-matlagningskurs', 'Akvariumbesök och kryssning', 'http://www.reseguiden.se/hotell/osaka/1853909 ', 'https://www.flygresor.se/japan/osaka', 'http://www.viator.com/Osaka/d333-ttd'),
(45, 'Tokyo', 'Japan', 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 'Asien', 1, 1, 1, 1, 'tokyo.jpg', 'sumobrottning.png', 'tokyo_tower.png', 'sightseeing.png', 'mat.png', 'Japan, japanska är det officiella språket i japan och yen är valutan som används. Medeltemperaturen vintertid i Japan ligger på 5,1 ºC och sommartid 25,2 ºC. Regnperioden börjar i maj - juni och når de nordliga regionerna i slutet av juli. Under denna period är luftfuktigheten hög och temperaturen kan på vissa ställen stiga till 42 ºC. Svenska medborgare som önskar resa till Japan som längst 90 dagar behöver inte ansöka om inresevisum i förväg om syftet med resan är följande icke-avlönade aktiviteter:\r\nturism, rekreation, utövande av amatörsport, besöka släktingar, deltaga i icke-betalda föredrag, konferenser eller möten, studier, affärsmöten, eller andra liknande aktiviteter. Journalister som reser till Japan för vistelse kortare än 90 dagar behöver inte heller ansöka om inrese-visum i förväg.\r\n \r\n· Det är oartigt att äta och dricka på gatan.\r\n· Om folk är för långsamma in i tåget så blir de inknuffade.\r\n· Butikerna är öppna dygnet runt\r\n· På vissa parkeringar så parkerar man bilen sen höjs rutan upp så att man tvingas betala för att få tillbaka bilen.\r\n· Om ett tåg är försenat med minst 30 sekunder så får alla åka gratis.', 'Tokyo ligger i Tokyoprefekturen i Kantregionen på östra Honsh och är Japans huvudstad. Tokyoområdet, Stortokyo, är med sina 35,7 miljoner invånare världens folkrikaste storstadsområde (folkräkning år 2005).[2] Administrativt försvann staden Tokyo redan 1943, men begreppet Tokyo används ofta om de 23 särskilda innerstadskommunerna vmed sammanlagt cirka 9 miljoner invånare. Detta är Japans de facto-huvudstad.\r\n\r\nNamnet Tokyo betyder bokstavligen östra huvudstaden. Tokio är en äldre stavning som fortfarande används i vissa språk. I Tokyo finns Japans parlament och kejsarpalatset där den kejserliga familjen bor. Staden är även hemvist för landets samtliga största medieföretag med tidningar och TV-kanaler men även internationellt aktiva japanska företag som Sony, Mitsubishi och Honda.', 'tokyo_background.jpg', 'https://www.viatorcom.se/sv/7384/tours/Tokyo/Sumobrottning-i-Tokyo/d334-2142TYO_F550', 'https://www.viatorcom.se/sv/7384/tours/Tokyo/Dagstur-med-Tokyo-Tower-teceremoni-och-kryssning-pa-Sumidafloden/d334-2142TYO_A100', 'https://www.viatorcom.se/sv/7384/tours/Tokyo/Morgontur-med-sightseeing-i-Tokyo/d334-2142TYO_A010', 'https://www.viatorcom.se/sv/7384/tours/Tokyo/Kvaellstur-i-Tokyo-japansk-matrundtur/d334-5263JPUC', 'Sumobrottning', 'Tokyo Tower + kryssning', 'Morgon-sightseeing', 'Matrundtur', 'http://www.reseguiden.se/hotell/tokyo/1850147', 'https://www.flygresor.se/japan/tokyo', 'https://www.viatorcom.se/sv/7384/Tokyo/d334-ttd'),
(46, 'Bamako', 'Mali', 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 'Afrika', 1, 0, 0, 0, 'bamako.jpg', 'marknad.png', 'katedral.png', 'museum.png', 'park.png', 'Mali, franska är det officiella språket i landet. Klimatet är hett och torrt i hela Mali. I Saharaöknen i norr regnar det mycket sällan, vissa år faller ingen nederbörd alls. I Sahelområdet längre söderut är klimatet mindre torrt och medeltemperaturen är något lägre. I den sydligaste delen av landet är det svalare och fuktigare. I Mali är valutan CFA-franc.\r\nAlla nationaliteter behöver visum för inresa till Mali. Ett visum är giltigt för en inresa i landet och gäller i en månad från inresedagen i Mali, men kan förlängas på Migrationsverket i Bamako eller på en malisk polisstation. Visum kan erhållas upp till tre månader innan resan och erhålls från närmaste maliska ambassad eller konsulat.', 'Bamako är huvudstad i Mali, ligger vid floden Niger och har cirka 2,1 miljoner invånare (2013). Bamako utgör ett självständigtdistrikt, på samma administrativa nivå som landets regioner. Distriktet är indelat i sex administrativa kommuner, numrerade I till VI, som vidare är indelade i 68 stadsdelar. Staden grundades 1650.', 'bamako_background.jpg', 'https://www.tripadvisor.com/Attraction_Review-g293813-d556540-Reviews-Bamako_city_centre_market-Bamako.html', 'https://www.tripadvisor.com/Attraction_Review-g293813-d8070025-Reviews-Cathedral_of_Bamako-Bamako.html', 'https://www.tripadvisor.com/Attraction_Review-g293813-d2081099-Reviews-Musee_National_de_Bamako-Bamako.html', 'https://www.tripadvisor.com/Attraction_Review-g293813-d2320585-Reviews-Parc_national_du_Mali_Bamako-Bamako.html', 'City-marknad', 'Katedralbesök', 'Nationalmuseum', 'Nationalpark', 'http://www.reseguiden.se/hotell/bamako/2460596', 'http://www.skyscanner.se/flyg-till/bko/billiga-flyg-till-bamako-flygplats.html ', 'https://www.tripadvisor.com/Attractions-g293813-Activities-Bamako.html'),
(56, 'Buenos Aires', 'Argentina', 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 'Sydamerika', 1, 0, 0, 0, 'BA-city.jpg', 'BA-coocking.jpg', 'BA-tango.jpg', 'BA-arkitektur.jpg', 'BA-pub.jpg', 'Argentina, det officiella språket är spanska, det talas också italienska och några indianspråk, till exempel guaraní talas också. Klimatet växlar från subtropiskt i norr till nästan arktiskt i söder. Större delen av landet har dock ett tempererat klimat. På Pampas är det milt, vintertid går temperaturen sällan under noll och sommartid ligger medeltemperaturen över 20 grader. Vid kusten är luftfuktigheten hög, men inåt landet är klimatet torrare och temperaturväxlingarna tydligare. Valutan är argentinsk peso.\r\nFör vistelser under tre månader krävs inte något turistvisum för resenärer från de flesta länder. Resenärer uppmanas dock att kontakta sin lokala ambassad innan avresa. ', 'Buenos Aires är sedan 1880 huvudstad i republiken Argentina. Den är belägen vid Río de la Platas södra strand och har cirka 2,9 miljoner invånare i staden. Stadens centrum utgörs av ett eget federalt distrikt omges av provinsen Buenos Aires, vars huvudort La Plata ligger söder om Buenos Aires. Buenos Aires betyder ungefär "Den goda luften" eller "De goda vindarna".', 'Argentina-background.jpg', 'http://www.viator.com/tours/Buenos-Aires/Buenos-Aires-Cooking-Class/d901-5674P125', 'http://www.viator.com/tours/Buenos-Aires/Buenos-Aires-Dinner-and-Tango-Show/d901-5674TANGO', 'http://www.viator.com/tours/Buenos-Aires/Architectour/d901-26466P4', 'http://www.viator.com/tours/Buenos-Aires/Buenos-Aires-Pub-Crawl/d901-5674PUB', 'Matlagningskurs', 'Middag och tango show', 'Middag och tango show', 'Guidad pub-crawl', 'http://www.reseguiden.se/hotell/buenos-aires/3435910', 'https://www.flygresor.se/argentina/buenos-aires', 'http://www.viator.com/Buenos-Aires/d901-allthingstodo'),
(57, 'Cordoba', 'Argentina', 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 'Sydamerika', 1, 0, 0, 0, 'cordoba-city.jpg', 'Cordoba-mountain.jpg', 'Cordoba-punilla.jpg', 'Cordoba-jesuit.jpg', 'Cordoba-traslasierra.jpg', 'Córdoba är Argentinas näst största stad med cirka 1,5 miljoner invånare (2003). Staden är huvudstad i provinsen Córdoba. Córdoba är en stad med mångsidig industri. Där finns textil- och transportindustri. Staden är också ett kommunikations-, handels- och kulturcentrum belägen cirka 700 kilometer nordväst om huvudstaden Buenos Aires. Staden grundades 1573 och var en av jesuiternas huvudorter i det spanska Amerika. Landets äldsta universitet grundades 1613 i Córdoba.', 'Córdoba är Argentinas näst största stad med cirka 1,5 miljoner invånare (2003). Staden är huvudstad i provinsen Córdoba. Córdoba är en stad med mångsidig industri. Där finns textil- och transportindustri. Staden är också ett kommunikations-, handels- och kulturcentrum belägen cirka 700 kilometer nordväst om huvudstaden Buenos Aires. Staden grundades 1573 och var en av jesuiternas huvudorter i det spanska Amerika. Landets äldsta universitet grundades 1613 i Córdoba.', 'argentina-background.jpg', 'http://www.viator.com/tours/Cordoba/Sierras-Chicas-circuit-Half-Day-Tour-from-Cordoba/d22281-5674P145', 'http://www.viator.com/tours/Cordoba/Punilla-Valley-Full-Day-Tour-from-Cordoba/d22281-5674P147', 'http://www.viator.com/tours/Cordoba/Full-Day-Jesuit-Legacy-Tour-from-Cordoba/d22281-5674P140', 'http://www.viator.com/tours/Cordoba/Traslasierra-Valley-Full-Day-Tour-from-Cordoba/d22281-5674P148', 'Guidad tur bland bergen', 'Heldagstur i Punilla-dalen', 'Heldagstur i Punilla-dalen', 'Heldags guidad tur i Traslasierra dalen', 'http://www.reseguiden.se/hotell/cordoba/2519240', 'http://www.reseguiden.se/flyg/cordoba/cor', 'https://www.viatorcom.se/sv/7384/Cordoba/d5254-ttd'),
(58, 'Caracas', 'Venezuela', 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 'Sydamerika', 1, 0, 0, 0, 'caracas-city.jpg', 'caracas-cablecar.jpg', 'caracas-avila.jpg', 'caracas-topotepuy.jpg', 'caracas-history.jpg', 'Venezuela, Venezuelas Bolivar Fuerte är valutan i Venezuela (VE, VEN). Det officiella språket är spanska och utöver det finns 30 olika indianspråk. Större delen av Venezuela ligger i den tropiska zonen men de stora höjdskillnaderna gör att klimatet varierar. Låglandet är varmt, medan bergsområdena är svalare.\r\nInget visum krävs men man behöver fylla i ett gratis turist kort (”tarjeta de ingresso”) också betecknat som ett DEX-2, för att få resa in i landet. Korten utfärdas normalt till inkommande flygpassagerare men hittas vid alla gränskontroller.', 'Caracas är huvudstaden i Venezuela, och huvudort för Venezuelas huvudstadsdistrikt. Staden är belägen i norra delen av landet i en dalgång mellan två bergskedjor, tio kilometer från Karibiska havet. Staden ligger cirka 1 000 meter över havet och har ett behagligt klimat.\r\nCaracas är Venezuela administrativa, ekonomiska och kulturella centrum och har, främst till följd av landets oljeboom, haft en snabb tillväxt efter andra världskriget. Stadsbilden är modern med breda motorvägar och höghus, men stora slumområden breder ut sig på sluttningarna runt stadskärnan. Industrin, bland annat bilfabriker, livsmedels- och kemisk produktion, ligger framförallt i förstäderna. Motorväg förbinder Caracas med hamnstaden La Guaira och den internationella flygplatsen vid kusten. Staden har flera universitet och högskolor, museer och bibliotek.', 'venezuela-bakgrund.jpg', 'http://www.viator.com/tours/Caracas/Caracas-Sightseeing-Tour-Including-Cable-Car-Ride-and-Lunch/d25981-18605P7', 'http://www.viator.com/tours/Caracas/Half-Day-Tour-Avila/d25981-18605P3', 'http://www.viator.com/tours/Caracas/Full-Day-Topotepuy-El-Hatillo-Tour/d25981-18605P4', 'http://www.viator.com/tours/Caracas/Half-Day-Historical-Tour-of-Caracas/d25981-18605P5', 'Guidad Sight-seeing tur och Cable car åk', 'Guidad Jeep tur i El Ávila National Parken', 'Guidad Jeep tur i El Ávila National Parken', 'Guidad tur i Caracas historiska delar', 'http://www.reseguiden.se/hotell/caracas/3646738', 'https://www.flygresor.se/venezuela/caracas', 'https://www.viatorcom.se/sv/7384/Caracas/d25981-ttd'),
(59, 'Maracaibo', 'Venezuela', 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 'Sydamerika', 1, 0, 0, 0, 'maracaibo-background.jpg', 'maracaibo-climbing.jpg', 'maracaibo-spa.jpg', 'maracaibo-spa.jpg', 'maracaibo-museum.jpg', 'Venezuela, Venezuelas Bolivar Fuerte är valutan i Venezuela (VE, VEN). Det officiella språket är spanska och utöver det finns 30 olika indianspråk. Större delen av Venezuela ligger i den tropiska zonen men de stora höjdskillnaderna gör att klimatet varierar. Låglandet är varmt, medan bergsområdena är svalare.\r\n\r\nInget visum krävs men man behöver fylla i ett gratis turist kort (”tarjeta de ingresso”) också betecknat som ett DEX-2, för att få resa in i landet. Korten utfärdas normalt till inkommande flygpassagerare men hittas vid alla gränskontroller.', 'Maracaibo är en stad i västra Venezuela, och är den administrativa huvudorten för delstaten Zulia. Den är den näst största staden i landet och är belägen vid Maracaibosjön, som trots sitt namn är en havsvik. Maracaibo grundades 1529.', '', 'http://www.summitpost.org/piedras-blancas/691622', 'http://discoverwhattodo.com/caracas-venezuela/canoe-kayak-river-tours-rentals-caracas-venezuela.htm', 'http://www.spalatinomaracaibo.com/', 'http://www.world-guides.com/latin-america/venezuela/zulia/maracaibo/maracaibo_museums.html', 'Bergsklättring', 'Kanot- och kajakpaddling', 'Kanot- och kajakpaddling', 'Museum', 'http://www.sembo.se/d/hotell/venezuela/venezuela/maracaibo', 'http://www.reseguiden.se/flyg/maracaibo/mar', 'https://www.tripadvisor.se/Attractions-g316092-Activities-Maracaibo_Zulian_Region.html'),
(60, 'Valencia', 'Venezuela', 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 'Sydamerika', 1, 0, 0, 0, 'valencia-city.jpg', 'valencia-dykning.jpg', 'valencia-lake.jpg', 'Valencia-park.jpg', 'valencia-dunas.jpg', 'Venezuela, Venezuelas Bolivar Fuerte är valutan i Venezuela (VE, VEN). Det officiella språket är spanska och utöver det finns 30 olika indianspråk. Större delen av Venezuela ligger i den tropiska zonen men de stora höjdskillnaderna gör att klimatet varierar. Låglandet är varmt, medan bergsområdena är svalare.\r\n\r\nInget visum krävs men man behöver fylla i ett gratis turist kort (”tarjeta de ingresso”) också betecknat som ett DEX-2, för att få resa in i landet. Korten utfärdas normalt till inkommande flygpassagerare men hittas vid alla gränskontroller.', 'Valencia är en stad i norra Venezuela, och är den administrativa huvudorten för delstaten Carabobo. Den är belägen strax väster om Valenciasjön, landets näst största insjö. Valencia grundades av spanjorerna den 22 mars 1555 under namnet Nuestra Señora de la Asunción de Nueva Valencia del Rey.', '', 'http://www.travellosroques.com/paseos/los_roques/13.html', 'http://earthobservatory.nasa.gov/IOTD/view.php?id=5001', 'https://www.tripadvisor.com.au/Attraction_Review-g316069-d3366835-Reviews-Parque_Fernando_Penalver-Valencia_Central_Region.html', 'http://www.parquedunas.com.ve/#_=_', 'Dykning', 'Största sötvatten sjön i Venezuela, Lago de Valencia', 'Största sötvatten sjön i Venezuela, Lago de Valencia', 'Stort badhus/waterpark', 'https://tinyurl.com/heguyun', 'http://www.reseguiden.se/flyg/valencia/vln', 'https://www.tripadvisor.se/Attractions-g316065-Activities-c42-Central_Region.html'),
(61, 'Djenne', 'Mali', 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 'Afrika', 1, 0, 0, 0, 'djenne-city.jpg', 'djenne-moské.jpg', 'djenne-oldtown.jpg', 'djenne-house.jpg', 'djenne-omnejd.jpg', 'Mali, franska är det officiella språket i landet. Klimatet är hett och torrt i hela Mali. I Saharaöknen i norr regnar det mycket sällan, vissa år faller ingen nederbörd alls. I Sahelområdet längre söderut är klimatet mindre torrt och medeltemperaturen är något lägre. I den sydligaste delen av landet är det svalare och fuktigare. I Mali är valutan CFA-franc.\r\n\r\nAlla nationaliteter behöver visum för inresa till Mali. Ett visum är giltigt för en inresa i landet och gäller i en månad från inresedagen i Mali, men kan förlängas på Migrationsverket i Bamako eller på en malisk polisstation. Visum kan erhållas upp till tre månader innan resan och erhålls från närmaste maliska ambassad eller konsulat.', 'Djenné är en stad vid floden Bani i Mopriregionen i södra Mali. Folkmängden i kommunen\r\nuppgick till 30 392 invånare 2013. Den är berömd för sina byggnader i lera, varav den mest kända är Djennés stora moské, återuppbyggd 1907. Förr i tiden var Djenné centrum för handel och kunskap, och erövrades ett antal gånger sedan grundandet. Under regnperioden blir Djenné en ö. Den gamla staden i Djenné sattes 1988 upp på Unescos världsarvslista.', 'mali-bakgrund.jpg', 'https://www.khanacademy.org/humanities/art-africa/west-africa/mali1/a/great-mosque-of-djenn', 'http://whc.unesco.org/en/list/116', 'http://www.djennetourism.com/places-of-interest/', 'http://www.djennetourism.com/surroundings/', 'Djennes stora moské', 'Djennes äldre stadsdelar', 'Djennes äldre stadsdelar', 'Djennes omnejder', 'https://www.tripadvisor.se/Hotels-g480205-c2-Djenne_Mopti_Region-Hotels.html', 'https://www.skyscanner.se/flyg-till/bko/billiga-flyg-till-bamako-flygplats.html', 'https://www.tripadvisor.se/Attractions-g480205-Activities-Djenne_Mopti_Region.html');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `countries`
--
ALTER TABLE `countries`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `countries`
--
ALTER TABLE `countries`
  MODIFY `id` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=62;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
